name: Push to Mirror Repos
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  push-to-other-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name:
        run: |
          git remote add gitlab https://gitlab.com/Renegade-Master/dotfiles.git
          git push gitlab master
