name: Push to Mirror Repos
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  push-to-other-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to GitLab
        uses: kujov/gitlab-sync@2
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username: ${{ secrets.USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
